### ISSUE TITLE
maintaining state between steps

### ISSUE THREAD

**Issue by skndn60** [imtapps/django-wizard#1]
I want to use the wizard to construct an object where the data collection and validation spans multiple steps. It's important to retain the state between the various steps. The last step of the wizard should be the save operation where the collected data from previous steps is gathered and used to assemble the new instance. Is this possible with the current implementation?

**Comment by imtapps** [comment]
I think Django's built-in [form wizard](https://docs.djangoproject.com/en/dev/ref/contrib/formtools/form-wizard/) might be what you're wanting. [This project](https://github.com/imtapps/django-wizard) is geared more towards managing page flow. Hope this helps!
